#!/usr/bin/env bash
# debugging nginx to listen to port 80
sed -i "s/listen 8080 default_server;\n\tlisten \[::\]:8080 default_server ipv6only=on;/listen 80 default_server;\n\tlisten \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
service nginx start
pkill -o nginx
